# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Framework
version:      1.228
version_from: lib/Class/Framework.pm
installdirs:  site
requires:
    Class::Accessor:               0
    fields:                        0
    NEXT:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
